### ISSUE TITLE
resource suggestion

### ISSUE THREAD

**Issue by WeileiZeng** [brentjackson/OpenIntubator#2]
https://coronavirustechhandbook.com/
This is a great list. It also have sections for doctors, nurses, etc. This would a good starting point, either to contribute to their list, or build something based on their collections.

**Comment by brentjackson** [comment]
Thanks so much... entered into Resources wiki page.
(As a collaborator, you have access to edit the wiki pages as well. Hoping you and others will do that going forward so that progress doesn't bottleneck on me.)

**Comment by WeileiZeng** [comment]
Thanks for the invitation. I am currently maintaining other pages as well. Also, my local situation is changing everyday. I am not sure about my commitment for this project, but would be willing to help in the future if possible.
